#BlueJ properties. Settings in this file override "bluej.defs"
#Sun Mar 22 20:32:42 EDT 2026
blackbox.uuid=a92928b4-5ff7-4fec-ac70-941f5f112d78
bluej.language=english
bluej.startWithTextEval=false
bluej.uid=230c2f17-11e0-4a12-a04c-75408836ba2c
extensions.org.bluej.extensions.submitter.Submitter.settings.saslrealm=
session.numeditors.java=0
session.numeditors.stride=0
